project_id = "tdoyunayplyrmdixhvmn"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-cert-expirations]
    verify_jwt = false
  [functions.expire-deposit-balances]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.send-auto-email]
    verify_jwt = false
  [functions.send-teaching-schedule]
    verify_jwt = false
